name: Publish to TestPyPI

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to Test-PyPI
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Verify version matches tag
        run: |
          VERSION=$(poetry version -s)
          TAG=${GITHUB_REF#refs/tags/}
          if [ "$VERSION" != "$TAG" ]; then
            echo "Error: Version in pyproject.toml ($VERSION) does not match tag ($TAG)"
            exit 1
          fi
      - name: Build
        run: |
          poetry build
      - name: Publish to Test-PyPI
        if: github.event_name == 'release' && ( github.ref_name =~ '^refs/tags/[0-9]+\\.[0-9]+\\.[0-9]+$' || github.ref_name =~ '^refs/tags/[0-9]+\\.[0-9]+\\.[0-9]+-rc[0-9]+$' )
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
