name: Publish to TestPyPI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/${{ github.event.repository.name }}
    permissions:
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Verify version matches tag
      run: |
        VERSION=$(poetry version -s)
        TAG=${GITHUB_REF#refs/tags/}
        if [ "$VERSION" != "$TAG" ]; then
          echo "Error: Version in pyproject.toml ($VERSION) does not match tag ($TAG)"
          exit 1
        fi

    - name: Build
      run: |
        poetry build

    - name: Publish to Test-PyPI
      uses: pypa/gh-action-pypi-publish@3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f
