name: Publish to TestPyPI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/${{ github.event.repository.name }}
    permissions:
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Verify version matches tag
      run: |
        VERSION=$(poetry version -s)
        TAG=${GITHUB_REF#refs/tags/}
        if [ "$VERSION" != "$TAG" ]; then
          echo "Error: Version in pyproject.toml ($VERSION) does not match tag ($TAG)"
          exit 1
        fi

    - name: Build and publish to TestPyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        poetry build
        poetry publish
