name: Version Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'pyproject.toml'

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Check version bump
      run: |
        # Get current version from pyproject.toml
        NEW_VERSION=$(poetry version -s)

        # Get the latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        LATEST_VERSION=${LATEST_TAG#v}

        # Compare versions
        if [ "$(printf '%s\n' "$LATEST_VERSION" "$NEW_VERSION" | sort -V | head -n1)" = "$NEW_VERSION" ]; then
          echo "Error: New version ($NEW_VERSION) must be greater than latest version ($LATEST_VERSION)"
          exit 1
        fi

        # Ensure version follows semantic versioning (X.Y.Z)
        if ! [[ $NEW_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Error: Version ($NEW_VERSION) must follow semantic versioning (X.Y.Z)"
          exit 1
        fi
